name: 'Post to Discourse Action'
description:
  'Post the contents of a file or a string as a reply to a discourse topic'
author: 'wwerner'

branding:
  icon: 'file'
  color: 'green'

# Define your inputs here.
inputs:
  discourse_url:
    description: 'your discourse instance domain, e.g. "community.acme.com'
    required: true
  discourse_topic_id:
    description: 'the ID of the Discourse topic to reply to'
    required: true
  discourse_api_key:
    description: 'your discourse API key. It needs `topics:write`` permissions'
    required: true
  discourse_user:
    description:
      'the discourse user on whose behalf the action should be executed'
    required: true
  content_file:
    description: 'the file to load the content to post from'
    required: false
  content:
    description: 'the string to post'
    required: false
  github_sha:
    description: 'short commit hash to be put into to post for traceability'
    required: true

runs:
  using: node20
  main: dist/index.js
