name: 'Post to Discourse Action'
description:
  'Post the contents of a file or a string as a reply to a discourse topic'
author: 'wwerner'

branding:
  icon: 'file'
  color: 'green'

# Define your inputs here.
inputs:
  discourse_url:
    description: 'Your discourse instance domain, e.g. "community.acme.com'
    required: true
  discourse_topic_id:
    description: 'The ID of the Discourse topic to reply to. Leave empty and set `discourse_post_id` to update the original post.'
    required: false
  discourse_post_id:
    description: 'The ID of the Discourse post to replace with the content given. Leave empty and set `discourse_topic_id` to add a new reply to the topic.'
    required: false
  discourse_api_key:
    description: 'Your discourse API key. It needs `topics:write` permissions'
    required: true
  discourse_user:
    description:
      'The discourse user on whose behalf the action should be executed'
    required: true
  content_file:
    description: 'The file to load the content to post from'
    required: false
  content:
    description: 'The string to post'
    required: false
  github_sha:
    description: 'Short commit hash to be put into to post for traceability'
    required: true

runs:
  using: node20
  main: dist/index.js
